### ISSUE TITLE
No € symbol ? Is there a way to add it ?

### ISSUE THREAD

**Issue by nicolinuxfr** [dreampulse/computer-modern-web-font#1]
Thanks for this webfont ! I'm trying to use it on my blog, but I have one problem : there is no € symbols in the font… As you can see here, it's a different version (I suppose standard sans-serif font) which is used : 

<img width="1430" alt="capture d ecran 2015-10-29 a 18 19 52" src="https://cloud.githubusercontent.com/assets/2078386/10826345/aefb6ad0-7e69-11e5-8543-acdbb841f3ee.png">

I know there are ways to add a € font using LaTeX (see [here, for instance](http://tex.stackexchange.com/questions/9866/latest-advice-on-the-euro-symbol)). I was wondering if there was a way to do the same with web fonts. Should I use a different font, or could you add the symbol (and maybe others missing) to the existing fonts ?

Thanks again !

**Comment by nicolinuxfr** [comment]
Well, nevermind, I found that Latin Modern is similar to Computer Modern, but with € support.

**Comment by dreampulse** [comment]
Oh Thank! Do you have a link to the latin montern web-font? So that I can add it?

**Comment by nicolinuxfr** [comment]
Sorry for the delay, here's the link I used : http://www.fontsquirrel.com/fonts/latin-modern-roman

**Comment by dreampulse** [comment]
Tanks
